services:
  api:
    container_name: capstone
    image: capstone_drintim
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=docker
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB=capstone
    depends_on:
      - db
  db:
    container_name: db_capstone
    image: postgres:12
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=capstone
    volumes:
      # - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./backend/:/code/src/app
      - /code/src/app/node_modules
# onde constar "atualizar, substituir pelos padrões adotados para o projeto"
