version: "3.9"

services:
  db:
    container_name: db_capstone
    image: postgres:12
    env_file:
      - ./.env
    ports:
      - 5432:5432

  api:
    container_name: capstone
    image: capstone_drintim
    build: ./
    depends_on:
      - db
    ports:
      - 3000:3000
    env_file:
      - ./.env
    volumes:
      - ./:/app/:rw
    environment:
      - IS_COMPOSE=true
